name: "Test Build Website"

on:
  push:
    branches:
      - main

jobs:
  lint:
    name: Run Linters
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true
      - name: Run linters
        run: |
          npm install
          npm run lint
  build-debug:
    name: Test Build (Debug)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true
      - name: Build project
        run: |
          npm install
          npm run dev
  build-production:
    name: Test Build (Production)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true
      - name: Build project
        run: |
          npm install
          npm run build